#端口配置
server:
  port: 5001

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: *******
    username: ***
    password: ***

  application:
    name: coldchain_controller

  #redis配置
  redis:
    #地址
    host: **
    #端口
    port: **
    #密码
    password: gopor123
    #超时(毫秒)
    timeout: 10000

  #mq
  rabbitmq:
    host: **
    port: **
    username: admin
    password: admin
    virtual-host: cold
    connection-timeout: 10000
    listener:
      direct:
        acknowledge-mode: auto
    publisher-confirm-type: correlated
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml

#netty
netty:
  #端口
  port: 5000

